# Generated by Django 4.0.4 on 2022-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsessionID', models.IntegerField()),
                ('raceDate', models.CharField(max_length=10)),
                ('trackID', models.IntegerField()),
                ('trackName', models.CharField(max_length=100)),
                ('leadChanges', models.IntegerField()),
                ('totalCautions', models.IntegerField()),
                ('cautionLaps', models.IntegerField()),
                ('greenLaps', models.IntegerField()),
                ('totalLaps', models.IntegerField()),
                ('series', models.CharField(max_length=50)),
                ('season', models.IntegerField()),
                ('roundNum', models.IntegerField()),
            ],
        ),
    ]
