# Generated by Django 4.0.4 on 2022-05-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0002_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='notes',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
