# Generated by Django 4.0.4 on 2022-05-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0003_points_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='points',
        ),
        migrations.DeleteModel(
            name='raceSession',
        ),
    ]
