# Generated by Django 4.0.4 on 2022-05-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('btdyScraper', '0004_delete_points_delete_racesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='raceSession',
            fields=[
                ('subsessionID', models.IntegerField(primary_key=True, serialize=False)),
                ('raceDate', models.CharField(max_length=10)),
                ('trackID', models.IntegerField()),
                ('trackName', models.CharField(max_length=100)),
                ('leadChanges', models.IntegerField()),
                ('totalCautions', models.IntegerField()),
                ('cautionLaps', models.IntegerField()),
                ('greenLaps', models.IntegerField()),
                ('totalLaps', models.IntegerField()),
                ('series', models.CharField(max_length=50)),
                ('season', models.IntegerField()),
                ('roundNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('startPosition', models.IntegerField()),
                ('finishPosition', models.IntegerField()),
                ('totalLapsLead', models.IntegerField()),
                ('incidents', models.IntegerField()),
                ('finishPoints', models.IntegerField()),
                ('lapsLeadPoints', models.IntegerField()),
                ('mostLapsLeadPoints', models.IntegerField()),
                ('polePoints', models.IntegerField()),
                ('winPoints', models.IntegerField()),
                ('stagePoints', models.IntegerField()),
                ('winFlag', models.IntegerField()),
                ('poleFlag', models.IntegerField()),
                ('stageFlag', models.IntegerField()),
                ('mostLapsLeadFlag', models.IntegerField()),
                ('topFiveFlag', models.IntegerField()),
                ('topTenFlag', models.IntegerField()),
                ('payoutAmount', models.IntegerField()),
                ('avgLap', models.IntegerField()),
                ('avgLapFlag', models.IntegerField()),
                ('roundNum', models.IntegerField()),
                ('notes', models.TextField()),
                ('subsessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btdyScraper.racesession')),
            ],
        ),
    ]
