# Generated by Django 4.0.4 on 2022-06-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0006_points_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
