# Generated by Django 4.0.4 on 2022-06-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0007_points_totalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='lapsComp',
            field=models.IntegerField(default=0),
        ),
    ]
