# Generated by Django 4.0.4 on 2022-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0008_points_lapscomp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='notes',
            new_name='penaltyNotes',
        ),
        migrations.AddField(
            model_name='points',
            name='bonusNotes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
