# Generated by Django 4.1 on 2022-09-07 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btdyScraper', '0009_rename_notes_points_penaltynotes_points_bonusnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueName', models.CharField(max_length=50)),
                ('leagueOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesName', models.CharField(max_length=50)),
                ('pointsConfig', models.CharField(max_length=50)),
                ('payoutFlag', models.IntegerField(default=0)),
                ('bonusFlag', models.IntegerField(default=0)),
                ('payoutConfig', models.CharField(max_length=50)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('leagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btdyScraper.league')),
            ],
        ),
    ]
