# Generated by Django 4.1 on 2022-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0010_league_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='leagueUrl',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
