# Generated by Django 4.1 on 2022-09-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btdyScraper', '0012_series_seriesurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesession',
            name='series',
        ),
        migrations.AddField(
            model_name='racesession',
            name='seriesID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='btdyScraper.series'),
        ),
    ]
